# Generated by Django 3.1.7 on 2021-03-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='allModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('Artwork', 'Artwork'), ('Book', 'Book'), ('Coin', 'Coin'), ('Fossil', 'Fossil'), ('Jewelry', 'Jewelry'), ('Medal', 'Medal'), ('Meteorite', 'Meteorite'), ('Photo', 'Photo'), ('Pottery', 'Pottery'), ('Sculpture', 'Sculpture'), ('Weapon', 'Weapon')], max_length=10)),
            ],
        ),
    ]
