# Generated by Django 3.2 on 2021-04-11 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100)),
                ('attribute_content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_10_content',
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_10_name',
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_1_content',
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_1_name',
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_2_content',
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_2_name',
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_3_content',
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_3_name',
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_4_content',
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_4_name',
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_5_content',
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_5_name',
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_6_content',
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_6_name',
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_7_content',
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_7_name',
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_8_content',
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_8_name',
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_9_content',
        ),
        migrations.RemoveField(
            model_name='optionalattributes',
            name='attribute_9_name',
        ),
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.ImageField(default='catalogue_pics/null.PNG', upload_to='catalogue_pics'),
        ),
        migrations.AddField(
            model_name='optionalattributes',
            name='attribute_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attr_1', to='Catalogue.attribute'),
        ),
        migrations.AddField(
            model_name='optionalattributes',
            name='attribute_10',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attr_10', to='Catalogue.attribute'),
        ),
        migrations.AddField(
            model_name='optionalattributes',
            name='attribute_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attr_2', to='Catalogue.attribute'),
        ),
        migrations.AddField(
            model_name='optionalattributes',
            name='attribute_3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attr_3', to='Catalogue.attribute'),
        ),
        migrations.AddField(
            model_name='optionalattributes',
            name='attribute_4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attr_4', to='Catalogue.attribute'),
        ),
        migrations.AddField(
            model_name='optionalattributes',
            name='attribute_5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attr_5', to='Catalogue.attribute'),
        ),
        migrations.AddField(
            model_name='optionalattributes',
            name='attribute_6',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attr_6', to='Catalogue.attribute'),
        ),
        migrations.AddField(
            model_name='optionalattributes',
            name='attribute_7',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attr_7', to='Catalogue.attribute'),
        ),
        migrations.AddField(
            model_name='optionalattributes',
            name='attribute_8',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attr_8', to='Catalogue.attribute'),
        ),
        migrations.AddField(
            model_name='optionalattributes',
            name='attribute_9',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attr_9', to='Catalogue.attribute'),
        ),
    ]
