# Generated by Django 3.1.7 on 2021-02-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fossil',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Catalogue.basemodel'),
        ),
    ]
