# Generated by Django 3.1.7 on 2021-03-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0002_allmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmodels',
            name='model_type',
            field=models.CharField(choices=[('Artwork', 'Artwork'), ('Book', 'Book'), ('Coin', 'Coin'), ('Fossil', 'Fossil'), ('Jewelry', 'Jewelry'), ('Medal', 'Medal'), ('Meteorite', 'Meteorite'), ('Photo', 'Photo'), ('Pottery', 'Pottery'), ('Sculpture', 'Sculpture'), ('Weapon', 'Weapon')], max_length=11),
        ),
    ]
