# Generated by Django 3.1.7 on 2021-02-28 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Catalogue', '0002_auto_20210228_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='staff_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fossil',
            name='base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogue.basemodel'),
        ),
    ]
